import { Inter } from "next/font/google";
import "./globals.css";
import Theming from "@/Theme/Theming";
import HeadPage from "./components/HeadPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Staryum - Waitlist Mode",
  description: "Generated by Clodron Web Agency",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theming>
          <HeadPage />
          {children}
        </Theming>
      </body>
    </html>
  );
}
